#%RAML 1.0 Library
usage:
traits:
  correlationId:
    headers:
      correlationId:
        type: string
        example: 79a4126a9576ff
  channel:
    headers:
      channel:
        type: string
        example: mobile
  client-credentials-required:
    headers:
      client_id:
        type: string
        example: 7b404180fbb84b099179a4126a9576ff
        required: true
      client_secret:
        type: string
        example: e241f4aa3eca4b2a8FA67A2FEF5754F8
        required: true
  standard-error-responses:
    responses:
      400:
        description:
          The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "BAD_REQUEST", 
                "ErrorMessage": "Bad Request",  
                "ErrorDescription": "HTTP GET on resource ‘HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx’ failed: bad request (400)"
              }
      401:
        description:
          The supplied credentials are invalid.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "UNAUTHORIZED", 
                "ErrorMessage": "please contact MuleSoft admin for further investigation",  
                "ErrorDescription": "HTTP GET on resource ‘HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx’ failed: unauthorized (401)"
              }
      403:
        description:
          There is a problem with the credentials that were provided.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "FORBIDDEN", 
                "ErrorMessage": "please contact MuleSoft admin for further investigation",  
                "ErrorDescription": "HTTP GET on resource ‘HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx’ failed: forbidden (403)"
              }
      404:
        description:
          The server cannot find the requested resource.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "NOT_FOUND", 
                "ErrorMessage": "please contact MuleSoft admin for further investigation",  
                "ErrorDescription": "HTTP GET on resource 'HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx' failed: not found (404)."
              }
      405:
        description:
          A request was made of a resource using a request method not supported by that resource; for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.
        body:
          application/json: 
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "METHOD_NOT_ALLOWED", 
                "ErrorMessage": "Method not allowed",  
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: method not allowed(405)"
              }
      406:
        description:
          The target resource does not have a current representation that would be acceptable to the user agent.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "NOT_ACCEPTABLE", 
                "ErrorMessage": "Not acceptable",  
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: not acceptable(406)"
              }
      415:
        description:
          The accept header specified an unsupported media type.
        body:
          application/json: 
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "UNSUPPORTED_MEDIA_TYPE", 
                "ErrorMessage": "Unsupported media type",  
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: unsupported media type(415)"
              }
      500:
        description:
          An internal processing error occurred while processing the API request.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "INTERNAL_SERVER_ERROR", 
                "ErrorMessage": "please contact MuleSoft admin for further investigation",  
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: internal server error(500)"
              }
      597:
        description:
          Experience API timeout during dependent service invocation.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "TIMEOUT", 
                "ErrorMessage": "Experience API Dependent Service Timeout",    
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: Timeout exceeded"
              }
      598:
        description:
          Process API timeout during dependent service invocation.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "TIMEOUT", 
                "ErrorMessage": "Process API Dependent Service Timeout",    
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: Timeout exceeded"
              }
      599:
        description:
          System API timeout during dependent service invocation.
        body:
          application/json:
            example: |
              { 
                "CorrelationId": "e241f4aa3eca4b2a8FA67A2FEF5754F8",
                "ErrorCode": "TIMEOUT", 
                "ErrorMessage": "System API Dependent Service Timeout",    
                "ErrorDescription": "HTTPS://app.ticketmaster.com/sth-customer/ticketing_services.aspx failed: Timeout exceeded"
              }