name: Single Branch MULTIENV build and deploy

on:
  push:
    branches: master 
#normally you wouldn't be deploying master branch pushes to Sandbox,
#but we're keeping things simple! 😁

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
  PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT}}

jobs:
  BuildAndDeployToDev:
    runs-on: ubuntu-latest
    environment:
      name: Sandbox
    steps:
#first, we need to checkout our mule application's code
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -s .maven/settings.xml
      - name: upload Artifact
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: Deploy
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
  
  DeployToUat:
    runs-on: ubuntu-latest
    environment: 
      name: UAT
    needs: [BuildAndDeployToDev]
    steps:
    #first, we need to checkout our mule application's code
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: cache dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -s .maven/settings.xml
      - name: Deploy
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml